version: 2.1
orbs:
  node: circleci/node@3.0.0

references:
  workspace_root: &workspace_root ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: *workspace_root
      paths: .

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn --frozen-lockfile --ignore-scripts
      - run: yarn lerna bootstrap
      - run: yarn lerna run build --concurrency=2 # prevent out-of-memory
      - *persist_to_workspace

  test:
    executor: node/default
    steps:
      - *attach_workspace
      - run: yarn lint
      - run: yarn format:all
      - run: yarn tsc
      - run: yarn test:all --coverage --runInBand
      - run: '[ $COVERALLS_REPO_TOKEN ] && yarn coveralls < demo/coverage/lcov.info || true'
      - *persist_to_workspace

  deploy:
    executor: node/default
    environment:
      NODE_DEBUG: gh-pages
    steps:
      - *attach_workspace
      - run: yarn build:demo
      - run: utils/scripts/deploy.js

  publish:
    executor: node/default
    steps:
      - *attach_workspace
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: yarn lerna publish from-git --ignore-scripts --no-verify-access --yes

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          context: writer
      - publish:
          requires:
            - test
          context: maintainer
          filters:
            branches:
              only: master
